# api:
#     image: bite/api
#     ports:
#         - 8080:8080
#     links:
#         - bite_db
db:
    image: mysql/mysql-server:latest
    environment:
        MYSQL_ROOT_PASSWORD: bite123!
        MYSQL_DATABASE: bite
    ports:
        - 3306:3306
admin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: bite123!    
